export const quoteData = [
  'Does he look like a bitch?',
  'What do they call a Whopper? I dunno, I didnt go into Burger King.',
  `"What" aint no country Ive ever heard of. They speak English in "What"?`,
  'English, motherf**ker, do you speak it?',
  'Say what again. Say what again, I dare you, I double dare you motherf**ker, say what one more Goddamn time!',
  `Zed's dead, baby. Zed's dead.`,
  'Any of you f**ing pricks move, and Ill execute every motherf**king last one of ya!',
  'If my answers frighten you then you should cease asking scary questions.',
  'Ima get medieval on your ass.',
  `That's when you know you've found somebody special. When you can just shut the f**k up for a minute and comfortably enjoy the silence.`,
  `What does Marcellus Wallace look like?`,
  `So he hid it, in the one place he knew he could hide something: his ass. Five long years, he wore this watch up his ass.`,
  `The path of the righteous man is beset on all sides by the inequities of the selfish and the tyranny of evil men.`,
  `Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children.`,
  `And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers, And you will know my name is the Lord when I lay my vengeance upon thee!`,
  `That's a pretty f**king good milkshake. I don't know if it's worth five dollars but it's pretty f**king good.`,
  `I'm sorry. Did I break your concentration? Oh, you were finished. Well allow me to retort.`,
  `I hid this uncomfortable hunk of metal up my ass two years.`,
  `Be cool Honey Bunny!`,
  `Because you are a character doesn't mean the you have character.`,
  `What does Marsellus Wallace look like?`,
  `Royale with cheese.`,
  `That's thirty minutes away. I'll be there in ten.`
]
